### ISSUE TITLE
Unauthorized... even if i am

### ISSUE THREAD

**Issue by tijs** [codebutler/foursquarex#10]
Tried quite a few times to login but all i get is the unauthorized popup. The same credentials work fine with the iphone or web app so seems it's something in FoursquareX that is not working as intended?

**Comment by codebutler** [comment]
Hey... someone else mentioned a similar problem, hrm.
What happens if you put in your phone number instead of your email?

**Comment by tijs** [comment]
same thing. could be i typed it wrong the first time, but not the rest of the time; could it be saving the login details and then not overwriting them perhaps

**Comment by codebutler** [comment]
I tried deleting the prefs (`defaults delete com.codebutler.FoursquareX` from Terminal), then intentionally putting in the wrong login before the correct login, and I wasn't able to reproduce the problem...

My only thought at the moment is maybe the HTTP library I'm using has problems when the username (email/phone) or password has funky characters? If you think this might apply to your situation, would you mind helping out with the debugging by temporarily changing your pass and trying again? 

I'm about to step out the door, but I'll dig through the code later.

Thanks.

**Comment by cricketgeek** [comment]
I have no funky characters in my pass or username, I just installed the thing and got that message

**Comment by cricketgeek** [comment]
I ran that defaults delete command and then used the right username but invalid pass and the app loaded up fine, I looked in preferences and it appears to have stored my correct pass somewhere and probably used that, thus the working aspect

**Comment by tijs** [comment]
no funky chars in my pass or email just plain jane alphanumerics. tried deleting the prefs using your example command and by hand and then reentering the credentials but that does not fix it either.

**Comment by michelegera** [comment]
Same problem here :|

**Comment by danielfarrell** [comment]
Yeah, same thing here as well.  There is a number in my email address but nothing weird.

**Comment by ejw** [comment]
Yeah I get the same thing. Correct email and password and it simply does not work.

**Comment by codebutler** [comment]
Hi everyone!

Please try 0.5 from the following URL and let me know if it fixes the problem for you!
http://cloud.github.com/downloads/codebutler/foursquarex/FoursquareX-0.05.zip

Thanks for sticking around!

**Comment by maradatscha** [comment]
it fixed it for me!

**Comment by matzeller** [comment]
I had the same issue and the 0.05 release fixed it for me. Thanks!

**Comment by codebutler** [comment]
Good to hear! I'm closing this issue now, if you have any other problems, please open a new one.

Thanks!

**Comment by ejw** [comment]
Same. All fixed here too.

**Comment by michelegera** [comment]
Fixed! Thanks!

**Comment by andresus** [comment]
Same problem over here, and link to version 0.05 is denied: AccessDeniedAccess DeniedA85633A3DDD36814Ch6Jk7pfmB9cfyi8MUPhwQN3pR7Bef9eEImu4C/34bYndRav1YUjjb99oBm8VRtz

**Comment by andresus** [comment]
I cannot get this thing to work, whats happening? bests
