### ISSUE TITLE
Support OAuth authentication

### ISSUE THREAD

**Issue by codebutler** [codebutler/foursquarex#11]
Add support for OAuth instead of username/password.

http://groups.google.com/group/foursquare-api/web/oauth

**Comment by naveen** [comment]
+1 here

given the number of people interested in this (and that have already downloaded), it would be better to move to an oauth approach soon. (makes it a bit more secure for users – and makes it easier for me to track/rate/etc on the server-side)

**Comment by npdoty** [comment]
+1 
The warning message for users is a good precaution, but I suspect that a lot of people don't realize the danger of sending their usernames and passwords with every request.  I would really love it if this were fixed sooner rather than later.

**Comment by codebutler** [comment]
Hi everyone,

This pre-release build includes OAuth support. Please give it a try and let me know how if anything's wrong.

http://github.com/downloads/codebutler/foursquarex/FoursquareX-0.08.2.zip

Thanks,
Eric

**Comment by npdoty** [comment]
Hi Eric,

I'm eager to try out the OAuth support, but after installing that build, I can still only find the email address/password dialog. How do I authorize using OAuth?

Thanks,
Nick

**Comment by codebutler** [comment]
You need to enter your email/password once so FoursquareX can request the OAuth token. Your email/password isn't stored or used again.

**Comment by npdoty** [comment]
Ah, I see, I hadn't realized that Foursquare was promoting this non-standard method for desktop OAuth (http://groups.google.com/group/foursquare-api/web/oauth). It is good that you're not storing the password anymore or sending it with every request, but the user has no way to understand this (I can confirm it by looking through the source code, but I suspect that most of your users won't be able to do that) and it seems to lose the OAuth advantage of training users to only enter their passwords into the corresponding web site (see, for example, Fire Eagle's best practice document: http://fireeagle.yahoo.net/developer/documentation/oauth_best_practice).

Anyway, it is much better than before, so thanks for that.
Nick

**Comment by codebutler** [comment]
I agree with you, I don't think OAuth makes sense for desktop applications in most cases, and would've rather Foursquare just support https.

Anyway, thanks for testing, sounds like everything is working for you? I'll be pushing this out as v0.09 shortly.
- Eric

**Comment by npdoty** [comment]
Yes, authorizing with OAuth, getting friend's updates and checking in to a location are all working for me in this build.

I agree that HTTPS would be a big improvement, but I actually think supporting good old-fashioned browser-based OAuth for desktop apps would be great: I don't like the practice of giving my passwords to desktop app developers, not all of whom are as conscientious as you. :)

Nick
