### ISSUE TITLE
Venueless Checkins result in weird location on map

### ISSUE THREAD

**Issue by msingleton** [codebutler/foursquarex#12]
Venueless checkins (checkins with no venue info, just a name) cause the checkin to look like it's coming from somewhere in northern canada.

Here is a sample checkin being sent that causes the issue:

<checkin>
  <id>5647470</id>
  <created>Sat, 16 Jan 10 22:33:00 +0000</created>
  <shout>using fouresquareX on @jillcsteinberg mac</shout>
  <venue>
  <name>At Home</name>
  </venue>
  <user>
  <id>999</id>
  <firstname>Jon</firstname>
  <lastname>Steinberg</lastname>
  <photo>http://playfoursquare.s3.amazonaws.com/userpix_thumbs/999_1236951187.jpg</photo>
  <gender>male</gender></user><display>Jon S. @ At Home</display>
</checkin>

**Comment by msingleton** [comment]
XML got mangled -- here it is: http://gist.github.com/279065

**Comment by codebutler** [comment]
Check for lat/lng when adding checkins to map. Closed by 33f592bfcd02bdf950cf43c109b4ac1ed85be29b.
