### ISSUE TITLE
Preference to control distance/quantity of checkins on the map

### ISSUE THREAD

**Issue by ljharb** [codebutler/foursquarex#15]
There should be a preference to control how many of my friend's checkins appear and/or how far away from me the checkins should show up. Personally I'd like the map to show EVERY one of my friend's checkins. Would be a great visualization.

**Comment by codebutler** [comment]
v0.06.1 has two new options: "Show older checkins on map" and "Show friends in other cities". With both these options selected, you get all your friends checkins on the map. 

http://cloud.github.com/downloads/codebutler/foursquarex/FoursquareX-0.06.1.zip

Does this do what you have in mind?

**Comment by ljharb** [comment]
0.061 is telling me "Failed to find location. kCLErrorDomain error 0".

However, if the map would work, then those options would seem to take care of it.

**Comment by ljharb** [comment]
The map is working now - not sure why it wasn't before. I'm going to close this issue since this handles what I requested.

**Comment by codebutler** [comment]
Good to hear things are working, thanks for the update. Keep an eye on issue #19 regarding the strange "Failed to find location" error. I'm planning to look into that soon.
