### ISSUE TITLE
No visible window

### ISSUE THREAD

**Issue by djwhelan** [codebutler/foursquarex#23]
I installed FoursquareX 0.06 earlier today, and everything worked like a charm. This evening, upon restarting and relaunching, the application starts as normal. I can access the menus. I can set the preferences. But there is no window. Accessing the Window->Bring All to Front menu does nothing. Quitting and relaunching has no impact. Restarting has no impact.

Has anyone else seen this behavior? I am sure I can trash the prefs or reinstall to get it back to normal, but if there is something I can provide to show what is happening, it might help track down a bug.

**Comment by djwhelan** [comment]
Sorry, but I am not sure how to label this as a Bug. Call it user error....

**Comment by djwhelan** [comment]
Just a heads up that I deleted my preferences file and everything is working fine again. I will update if the problem occurs again.

**Comment by codebutler** [comment]
Okay, please do let me know if you have any other problems.

**Comment by artlung** [comment]
I'm having this problem. I trashed previous version, and then installed latest 0.06.1 and I'm having the same problem.

Where is the preferences file? I can't seem to find it in Library/Application Support. Spotlight search shows nothing else with "foursquare" in the name.

**Comment by codebutler** [comment]
The prefs file is at ~/Library/Preferences/com.codebutler.FoursquareX.plist. Is the menubar icon not showing up either?

**Comment by artlung** [comment]
I didn't see that before. Lost in my other icons. If I do "show map" from that icon it shows the map. I was using the menu on the right. May I suggest that it either use the right or the left menu, not both? Or have the option to show the map window in the "Window" menu.

**Comment by codebutler** [comment]
You're absolutely correct that there should be an option to show the map in the "Window" menu, I'll fix that for the next release.

What do you mean by right/left menu?

**Comment by artlung** [comment]
When I'm saying "right menu" "left menu" right menu is the icon at the top right, and the left menu is the standard application pulldowns on the left. Cool re: the change!
