### ISSUE TITLE
Show all checkins on map setting not persisted

### ISSUE THREAD

**Issue by craSH** [codebutler/foursquarex#25]
The "Show all checkins on map" setting is not properly persisted through application restarts. E.g. setting it to true, quit the application, and open the application, it will not be set.

**Comment by codebutler** [comment]
Improved "show old checkins" option, fixed other bugs.
- Added new option to show checkins from other cities (doesn't work yet).
- Wait until map html is loaded before starting FoursquareUpdater.
- Persist "show old checkins", show in Preferences window. Closed by f1221ab7522ab5eef4900fa4be5f0c9091c59b06.
- Don't touch other people's objects in highlightCheckinRow.
