### ISSUE TITLE
Checkin notification preferences not remembered

### ISSUE THREAD

**Issue by abraham** [codebutler/foursquarex#34]
When checking in at a venue I disable telling Twitter and Facebook. If I then restart FoursquareX and go to checkin at a venue the options to notify Twitter and Facebook are enabled again.

**Comment by codebutler** [comment]
Fixed issues with checkboxes in checkin/shout windows.
- Checkboxes weren't always being disabled when appropriate.
- Checkbox states weren't being remembered. Closed by de2e10b8ff78965e3dc33ff16c89f5e87cd45b14.
