### ISSUE TITLE
Add option to hide checkins in other cities

### ISSUE THREAD

**Issue by codebutler** [codebutler/foursquarex#4]
If option is set to hide:
- Dont' show growl notifications for checkins in other cities.
- Put checkins in a new "Friends in Other Cities" group at the bottom of the list, instead of sorting into the standard time-based categories.
- Don't show checkins in the map unless selected (same behavior as checkins > 3 hrs old).

Consider any checkins > 40,000 meteres from current location to be in another city.

**Comment by craSH** [comment]
I would like this! Its a bit silly having the map be zoomed out to show me friends in other cities.

**Comment by codebutler** [comment]
Implemented option to hide friends in other cities. Closed by 6b6f608c3fd23909fb8e3969114a9f4a387065fe.
