### ISSUE TITLE
Better app and menu icons

### ISSUE THREAD

**Issue by codebutler** [codebutler/foursquarex#6]
A slight modification of the foursquare logo would be nice for uniqueness, maybe just give it an aqua shine.

The menu icon should be black and white to fit in with the rest of the system.

**Comment by codebutler** [comment]
Partially fixed in 03e101b1678063098c9b541283dc4e0ee3f41026 which includes a new app icon.

A new menu icon is still needed!

**Comment by trevorcortez** [comment]
Consider maybe the [mayor crown](http://foursquare.com/img/icon_mayor.png)?
or maybe something like what [Tweetie iPhone](http://tctechcrunch.files.wordpress.com/2010/03/af3.png?w=280&h=420) is doing?
Both of which I think would look better in black/white

**Comment by codebutler** [comment]
Ooh I love the crown, great suggestion!

**Comment by trevorcortez** [comment]
I've forked the code and am updating the icon and a few other little UI things, then you can check it out and pull as desired.

**Comment by trevorcortez** [comment]
Added mayor icons in my fork 8bda187cda21854ee9218fe2ab2e4fa46e003d1d

**Comment by codebutler** [comment]
This will be fixed in v0.09, thanks to everyone who helped out.
