### ISSUE TITLE
Default Location

### ISSUE THREAD

**Issue by ptescher** [codebutler/foursquarex#8]
Sometimes a location cannot be found, there should be a default location in the preferences that gets chosen if this is the case.

**Comment by ljharb** [comment]
Alternatively, you should be able to click on the map to specify a location. If I don't want the app to detect it, then just like on the website I should be able to arbitrarily locate myself somewhere.

**Comment by codebutler** [comment]
Issue #20 covers this. I haven't yet decided exactly how everything will fit together, but it's high on my list.

**Comment by codebutler** [comment]
Merging this into issue #20.
